# GNU nano 8.4                                /etc/dnscrypt-proxy/dnscrypt-proxy.toml
# Empty listen_addresses to use systemd socket activation
listen_addresses = []
server_names = ['cloudflare-security', 'brahma-world']
#chatgpt:
fallback_resolvers = ['9.9.9.9:53', '149.112.112.112:53']
ignore_system_dns = true

require_dnssec = true
dnscrypt_servers = true
doh_servers = true
block_ipv6 = false   # keep false if you want IPv6
ipv6_servers = true


[query_log]
  file = '/var/log/dnscrypt-proxy/query.log'
#  log_level = 2
[nx_log]
  file = '/var/log/dnscrypt-proxy/nx.log'

[sources]
  [sources.'public-resolvers']
  url = 'https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md'
  cache_file = '/var/cache/dnscrypt-proxy/public-resolvers.md'
  minisign_key = 'This is a key but unsure if i should share... normal config will work for you dont worry:)'
  refresh_delay = 72
  prefix = ''
